アラートの実装
luck-tech/luck-frontend-basic-2022-todoapp pull request #11
Opened 2023-03-27 08:19 UTC by luck-tech

2023-03-30 18:25 UTC, luck-tech commented
valueに空入力(null)すると、それまでの部品でエラー「nullが読めない」が複数発動してしまいます。どう改変するべきなのでしょうか？
<img width="304" alt="スクリーンショット 2023-03-31 3 22 24" src="https://user-images.githubusercontent.com/71510837/228929188-5da
<img width="647" alt="スクリーンショット 2023-03-31 3 24 39" src="https://user-images.githubusercontent.com/71510837/228929743-4d1b0d1b-f378-4331-be9f-a9ae140528fb.png">
94ef2-9b23-496e-bd43-f2fa70267770.png">

2023-04-01 13:56 UTC, higashiji2000 reviewed
おそらく画像のエラーは今回の問題とは関係ないのではないかと思います。

---
`Cannot read ...` のエラーは、`null` に対するプロパティアクセスが不可能という旨を表しています。
これは、この部分の処理が始まる前に、`<input>`要素がアンマウントされているのが原因と考えられます。
エラーが発生している行の中で `inputRef.current.value` を読もうとしていますが、refに渡していたinput要素がすでに存在しないので `inputRef.current === null` になります。
つまり `null.value` を読もうとしていたので、上述のエラーが発生していたというわけです。

対処法:
```js
if (inputRef.current === null) {
  return
}
// 本来やりたい処理
```
みたいな感じで、エラーが発生している箇所の前でinputRefに値が入っていることを確認し、入っていない場合は早期リターンしてあげるとエラーが発生しなくなるとかんがえられます。

2023-04-01 13:56 UTC, Higashiji commented on src/components/Atoms/Alert/index.jsx
> +  opacity: ${(visible) => (visible ? "0" : "1")};
```suggestion
  opacity: ${(visible) => (visible ? "1" : "0")};
```
ここを変えたら動いたりしますかね？

2023-04-01 18:30 UTC, luck-tech commented
> おそらく画像のエラーは今回の問題とは関係ないのではないかと思います。
> 
> `Cannot read ...` のエラーは、`null` に対するプロパティアクセスが不可能という旨を表しています。 これは、この部分の処理が始まる前に、`<input>`要素がアンマウントされているのが原因と考えられます。 エラーが発生している行の中で `inputRef.current.value` を読もうとしていますが、refに渡していたinput要素がすでに存在しないので `inputRef.current === null` になります。 つまり `null.value` を読もうとしていたので、上述のエラーが発生していたというわけです。
> 
> 対処法:
> 
> ```js
> if (inputRef.current === null) {
>   return
> }
> // 本来やりたい処理
> ```
> 
> みたいな感じで、エラーが発生している箇所の前でinputRefに値が入っていることを確認し、入っていない場合は早期リターンしてあげるとエラーが発生しなくなるとかんがえられます。

`if (input.current.value !== null) {やりたい処理}`
で回避できないのは、null.valueにアクセスしようがないから !== nullかどうか確かめられないということですか？？

2023-04-01 18:44 UTC, luck-tech commented
<img width="497" alt="スクリーンショット 2023-04-02 3 44 19" src="https://user-images.githubusercontent.com/71510837/229308794-f134ff02-d13e-434d-ad56-0cb422ce7316.png">
あ、これでも怒られました。

2023-04-01 19:06 UTC, luck-tech commented
エラー文は出るようになりますが、こうなっちゃいます。transformもopacityも効いていないみたいなのですが、書き方が悪いんですかね。
<img width="618" alt="スクリーンショット 2023-04-02 3 52 55" src="https://user-images.githubusercontent.com/71510837/229309135-3984e391-272c-4419-8423-56d1b7e1c5e6
<img width="555" alt="スクリーンショット 2023-04-02 4 04 51" src="https://user-images.githubusercontent.com/71510837/229309610-455ea835-f7e4-4bef-8851-cc6e043d0e5d.png">
<img width="514" alt="スクリーンショット 2023-04-02 4 05 03" src="https://user-images.githubusercontent.com/71510837/229309614-44c88fde-b3ad-47da-a960-0a4fa9425d53.png">
.png">

2023-04-01 19:23 UTC, luck-tech commented on src/components/Atoms/Alert/index.jsx
> +  opacity: ${(visible) => (visible ? "0" : "1")};
空入力でエラー文が出るようになりました！
そもそもvisibleがfalseになってないみたいで、三項演算子のtrue側しか機能していないようです。
<img width="618" alt="229309135-3984e391-272c-4419-8423-56d1b7e1c5e6" src="https://user-images.githubusercontent.com/71510837/229309979-ef300ba4-ba85-443f-9680-34abae4fa36c.png">
<img width="555" alt="229309610-455ea835-f7e4-4bef-8851-cc6e043d0e5d" src="https://user-images.githubusercontent.com/71510837/229309980-8799da87-d269-42e8-ad71-802e2de5f185.png">
<img width="514" alt="229309614-44c88fde-b3ad-47da-a960-0a4fa9425d53" src="https://user-images.githubusercontent.com/71510837/229309981-7ca63a28-d029-4144-b8a7-ab431badce86.png">

2023-04-03 01:45 UTC, higashiji2000 commented on src/components/Atoms/Alert/index.jsx
> +  opacity: ${(visible) => (visible ? "0" : "1")};
```suggestion
  opacity: ${({visible}) => (visible ? "0" : "1")};
```
すみません、正しくはこうですね！

```suggestion
  opacity: ${(props) => (props.visible ? "0" : "1")};
```
もしくはこうです

2023-04-03 01:46 UTC, higashiji2000 commented
> if (input.current.value !== null) {やりたい処理}
で回避できないのは、null.valueにアクセスしようがないから !== nullかどうか確かめられないということですか？？

その理解で正しいです！

2023-04-03 01:47 UTC, higashiji2000 commented
https://github.com/luck-tech/luck-frontend-basic-2022-todoapp/pull/11#issuecomment-1493073338

もしかしたら `null` ではなく `undefined` になっているかもしれないので、ifの部分を以下のように変えてみてください。

```js
if (!inputRef.current) {
  return;
}
```

2023-04-04 11:05 UTC, luck-tech commented
Alertは表示されるようになりました！！！
エラーは解決しなかったです。一応アプリは問題なく動きます。

2023-04-05 03:48 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/229976368-70073c4b-f32d-4c79-af46-9a6f6ace7443.png)
Alertと入力部分がかぶってしまっているので、[お手本](http://shinonome.io/frontend-basic-2022-todoapp/)を参考に高さを調節してください。

2023-04-05 03:48 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +    }
```js
    inputRef.current.addEventListener("focusout", () => {
       if (!inputRef.current) {
          return;
        }
        onEditComplete(inputRef.current.value)
      }
    );
    inputRef.current.addEventListener("keydown", (e) => {
       if (!inputRef.current) {
          return;
        }
      if (e.key === "Enter") {
        onEditComplete(inputRef.current.value);
      }
    })
```

このようにイベントハンドラの中で早期リターンするようにすればエラーが出なくなる気がします。
試してみてください:pray:

2023-04-05 07:47 UTC, luck-tech commented on src/components/Atoms/Input/index.jsx
> +    }
イベント呼び出してるとこでリターンしなきゃ、そりゃ変わりませんよね
あざす！

2023-04-05 15:25 UTC, higashiji2000 approved these changes
LGTMです🎊

2023-04-05 15:42 UTC, merged